### ISSUE TITLE
Multi Select

### ISSUE THREAD

**Issue by juppdes** [marcosmoura/vue-material#10]
Sorry the question may be stupid, but there is the possibility of it using the "multiselect" already implemented?
Do you have any documentation explaining the properties of each component?

**Comment by marcosmoura** [comment]
Hi. No, it's not stupid, don't worry. 

No. Multi selection it's not there yet but I will prioritize because it's a must have. Also I am describing the API for each component to make it better to understand and I will release it in less than a week. 
I will create today some milestones to make easy to track what is going to be developed next. 

Thank you!

**Comment by juppdes** [comment]
I thank you the attention and support!

**Comment by marcosmoura** [comment]
Already implemented and will be shipped on the very next release (v0.3.0)

**Comment by juppdes** [comment]
Thanks !!
