### ISSUE TITLE
Masking on input forms

### ISSUE THREAD

**Issue by achernyak** [marcosmoura/vue-material#107]
Are there any plans to implement a way to apply masks to input fields? I was not able to accomplish this by the normal route. I was trying to use `v-bind:value` and `v-on:input`. I also tried applying a computed field to just `v-bind:value` without `v-on:input`, and that seemed to have no impact.

**Comment by marcosmoura** [comment]
Well. This will not be acomplished by Vue Material. You can create a directive for that. I recommend you to create a wrapper of this library: https://nosir.github.io/cleave.js/
You can also take a look here: https://github.com/vuejs/awesome-vue

**Comment by achernyak** [comment]
@marcosmoura sorry, if I wasn't clear. I was not suggesting a creation of a mask through Vue Material. I was suggesting a way to pass a function that would run when the input value changes. 

When I was applying a change through `v-on:input` to the value of `md-input`, It was getting overwritten by the `md-input-container` since the `onInput` function is defined separately inside the two components.  At least that's what I was able to gather from some experimenting.

**Comment by marcosmoura** [comment]
Well. You can try two things:
- To use the native events modifier: ```v-on:input.native``` or ```:input.native```. Then you can fire your own function. 
- To create a directive, like v-mask, and manipulate the value of the element. This is the best way since you can reuse this through your application and even make this as an open source library. 

Remember that on Vue land the directives are intended to be used for manipulate low level stuff on DOM elements. Masks are a great example of low level manipulation. 

I hope that you can achieve this on your project. :D

**Comment by marcosmoura** [comment]
Oh. Just to add: v-bind will not work. You should use v-model instead.

**Comment by achernyak** [comment]
Thank you so much for the help. I actually had no idea about the use of `.native`.

**Comment by marcosmoura** [comment]
Yeah. It's a trick thing. I will add this to the new documentation.

**Comment by jimmywarting** [comment]
would also like to have masked input
