### ISSUE TITLE
Can't use it when I finish read the "Getting Started"

### ISSUE THREAD

**Issue by ThomasSoloist** [marcosmoura/vue-material#128]
html
```
<script src="lib/vue-material.js"></script>
<link href="lib/vue-material.css" rel="stylesheet">
<script data-main="main" src="require.min.js" defer async="true"></script>

<md-button class="md-primary">Primary</md-button>
```

main.js
```
require(['../module/common'], function(common) {

    Vue.use(VueMaterial)

    Vue.material.theme.register('default', {
        primary: 'cyan',
        accent: 'pink'
    })
});
```

And nothing happend...

**Comment by marcosmoura** [comment]
For both cases you need to use the theme that you've created:

``` vue
<div v-md-theme="'default'"></div>
```

#### To use with Require.js:
Instead of calling the Vue Material script inside your HTML file you'll need to require it inside your script:
``` javascript
require(['../module/common', 'lib/vue-material.js'], function(common) {
  Vue.use(VueMaterial)

  Vue.material.theme.register('default', {
    primary: 'cyan',
    accent: 'pink'
  })
});
```

#### To use without Require.js:
In this case you need to call the Vue Material inside your HTML (like you did):

``` html
<script src="lib/vue-material.js"></script>
```

``` javascript
Vue.use(VueMaterial)

Vue.material.theme.register('default', {
  primary: 'cyan',
  accent: 'pink'
})
```

#### Or you can use some [vue-cli](https://github.com/vuejs/vue-cli) template:
I would recommend you to use (and learn) the vue-cli with one of the templates.

--------------------------------------

Tell me if this works for you.
Thanks!

**Comment by ThomasSoloist** [comment]
![screen](https://cloud.githubusercontent.com/assets/12109558/20781899/dc3e0f92-b7c1-11e6-9779-5387734953dd.png)

@marcosmoura Thanks, but after I tried, It still not work for me. I didn't know where is wrong...

**Comment by marcosmoura** [comment]
You didn't implemented like I said in the previous example. Take a look at the Require.js part. You should import Vue Material there too.
``` javascript
require(['../module/common', 'lib/vue-material.js'], function(common) {
  Vue.use(VueMaterial)

  Vue.material.theme.register('default', {
    primary: 'cyan',
    accent: 'pink'
  })
});
```
Also looks like that the CSS file it's not loaded. Can you take a look at this?

**Comment by ThomasSoloist** [comment]
It works, thank you very much. And I have tried the vue-cli, it's very cool. Thanks! 👍
