### ISSUE TITLE
Using select in Vue modal example?

### ISSUE THREAD

**Issue by craigvantonder** [marcosmoura/vue-material#139]
I wanted to use the [Vue example modal](https://vuejs.org/v2/examples/modal.html) in conjunction with the [Material select component](https://marcosmoura.github.io/vue-material/#/components/select).

I found that when the select is used in this case then the drop down will appear behind the modal window, it's position fixed to the main window that is layered under the modal:

![Illustrating the issue](http://i.imgur.com/XTnqQsE.png)

I made a [codepen](http://codepen.io/craigvantonder/pen/KNQBbr) where I was able to reproduce the issue.

Only work around I noticed is that z-index on the modal-mask (wrapping modal in the DOM) is 9998, making  the class md-select-content 9999 renders it above the modal instead of below:

    .md-select-content {
      z-index: 9999;
    }

Is there any better solution for this?

**Comment by marcosmoura** [comment]
Hey @craigvantonder 

Thanks for a such detailed description/Codepen. 
I have found that the bug is related with the z-index indeed. I fixed this in your [Codepen](http://codepen.io/vue-material/pen/WoMqqg).

Look that this modal is a third party code. And, if you want, I will release a new version of Vue Material (v0.4.0) tomorrow with a brand new md-dialog component.

Thanks.
