### ISSUE TITLE
Feature Request please allow Vee-Validate in md-input

### ISSUE THREAD

**Issue by DevEclipse** [marcosmoura/vue-material#197]
I think its also a good idea as an input component that has validations to

**Comment by marcosmoura** [comment]
Hi @DevEclipse.

This is not going to be part of Vue Material for some reasons:
* The validation can be different across different projects
* The validation should be defined and created using other logics
* Will increase (a lot) the complexity of Vue Material input, textarea, select, checkbox, radio, switch and other components that use v-model
* Will increase the Vue Material build size
* If VeeValidate or other validation lib updates I will need to support it and deal with the constants breaking changes
* VeeValidate is not from Vue team (but is a great implementation)

I will eventually support [vue-validator](https://github.com/kazupon/vue-validator) when the stable version come up.

Don't get me wrong. I've used VeeValidate and Vuelidate (I had a better experience with this one) and I had no problems to integrate with Vue Material. But I think that this should be a responsability of a project that is using Vue Material. 

Thanks. :)

**Comment by dohomi** [comment]
@marcosmoura One question about your future path of form validation: are you planning to have some built in validation? Because a form without validation is unlikely being used in production apps. Some recommendation inside of your docs would be great, because on the first view it looks you support some error validation through the display of the error classes. Thanks

**Comment by marcosmoura** [comment]
I don't have plans to develop a new validator component for now. But I'm planning to do some integrations with some libraries.

**Comment by jonataswalker** [comment]
Same here, a smooth integration with Vuelidate.

**Comment by marcosmoura** [comment]
I will try to integrate with vuelidate. :)

**Comment by dohomi** [comment]
Currently run my forms with vuelidate without problems.

**Comment by abelovic** [comment]
@DevEclipse @marcosmoura @dohomi @jonataswalker 

I came across this post since I was looking to do validations as well

Having looked at a few of the libraries above, @marcosmoura I don't think you should add validations into your library at all. Maybe you can show examples in you documentation, but definitely do not bloat your framework since it is easy enough to add an external library.

I ended up using vee-validate since it was very straight forward to implement and worked perfectly for me. 

For anyone else needing to do form validations this is all I had to do:

```
<md-input-container :class="{'md-input-invalid': errors.has('firstName') }" md-inline>

    <label>First Name</label>

    <md-input
        name="firstName"
        v-model="form.firstName"
        data-vv-name="firstName"
        data-vv-rules="required"
        v-validate
        required/>

    <span class="md-error">{{ errors.first('firstName') }}</span>

</md-input-container>
```
```  
export default {
    data() {
        return {
          form: {
            firstName: ''
        }
    }
}
```  

If you want to check if the form is valid before submitting, run the following method on the form submit event:

```
    methods: {
      validateBeforeSubmit() {

        this.$validator.validateAll().then(() => {

          alert('form submitted!');

        }).catch((err) => {

          console.log(err);

          alert('form has errors!');
        });
      }
```

Hopefully that helps :)
