### ISSUE TITLE
Display glitch switching page?

### ISSUE THREAD

**Issue by nocquidant** [marcosmoura/vue-material#279]
I've just started experimenting with Vue and found your library, which is pretty much what I was looking for (Polymer app-layout equivalent). I mimic your docs app, but I encounter a display glitch when changing from one page to another. See attachment, right after following the link: "Votre commande". Is there a force relayout or something I could avoid? 

![peek 2016-12-31 18-28](https://cloud.githubusercontent.com/assets/217054/21578625/ea4d9d5e-cf87-11e6-9aca-37e9ee4c9164.gif)

Help appreciated.
Thanks for your work.
--nick

**Comment by marcosmoura** [comment]
@nocquidant Which version of Vue are you using? There is "async" data loading?

**Comment by nocquidant** [comment]
The vue version I use is: 2.1.6
My simple project is here: https://github.com/nocquidant/shopping-list
But actually, I thing this is the same behavior as on your site: https://vuematerial.github.io/#/
If you scroll down and change page, for a fraction of second, you can see the content scroll to the top (before displaying the next page).

Thanks,
--nick

**Comment by korylprince** [comment]
@nocquidant You're seeing this "glitch" because you have a `<transition>` on your `<router-view>` in App.vue.

If you remove the `<transition>` you will see this glitch goes away. If you want to keep the transition, you'll need to fix the transition classes (.md-router-enter, etc) in App.vue.

My guess is one of the properties being animated (my guess is `left`) is causing the weirdness you are seeing.

**Comment by nocquidant** [comment]
Thanks for your help @korylprince, that was the transition effect.

**Comment by marcosmoura** [comment]
Nice. Thank you @korylprince.
