### ISSUE TITLE
import vue-material css file failed

### ISSUE THREAD

**Issue by lilien1010** [marcosmoura/vue-material#280]
as the demo code you set 
```
import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'
```
 
and the webpack is set  like below
```
  module: {
    preLoaders: [

    ],
    loaders: [
      {
      test: /\.css$/,
       include: /node_modules/,
       loader: 'style-loader!css-loader'
      }
    ]
  },

```

but it always shows an error like 
```
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/admin/Documents/learn/vue/vue2-test/node_modules/vue-material/dist/vue-material.js/dist/vue-material.css
```

**Comment by korylprince** [comment]
This is a problem with your webpack configuration, not vue-material. Can you post the whole thing? The fact that it's searching for the file at `node_modules/vue-material/dist/vue-material.js/dist/vue-material.css` instead of `node_modules/vue-material/dist/vue-material.css`  means something wonky is going on.

**Comment by lilien1010** [comment]
fixed! thanks
