### ISSUE TITLE
initialization error

### ISSUE THREAD

**Issue by mygnu** [marcosmoura/vue-material#3]
``` javascript
import Vue from 'vue'
import VueMaterial from 'vue-material'

Vue.use(VueMaterial)

Vue.material.theme.register('default', {
    primary: 'cyan',
    accent: 'pink'
})
```
gives you the following error
``` javascript
vue-material.js?ec92:6Uncaught TypeError: Cannot set property 'default' of undefined
register @ vue-material.js?ec92:6
(anonymous function) @ main.js?3479:10
(anonymous function) @ app.js:1230
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous function) @ app.js:587
__webpack_require__ @ app.js:556
(anonymous function) @ app.js:579
(anonymous function) @ app.js:582
```

**Comment by marcosmoura** [comment]
Hi Mygnu.

Can you try a different approach? Instead of register a single theme with
register() method try to, temporarily, use the registerAll with only one
theme, like:

Vue.material.theme.registerAll({
  default: {
    primary: 'cyan',
    accent: 'pink'
  }
})

Thank you for trying this project even before the finished documentation.

On Oct 14, 2016 21:56, "Mygnu" <notifications@github.com> wrote:
>
> import Vue from 'vue' import VueMaterial from 'vue-material'
Vue.use(VueMaterial) Vue.material.theme.register('default', { primary:
'cyan', accent: 'pink' })
>
> gives you the following error
>
> vue-material.js?ec92:6Uncaught TypeError: Cannot set property 'default'
of undefined register @ vue-material.js?ec92:6 (anonymous function) @
main.js?3479:10 (anonymous function) @ app.js:1230 __webpack_require__ @
app.js:556 fn @ app.js:87 (anonymous function) @ app.js:587
__webpack_require__ @ app.js:556 (anonymous function) @ app.js:579
(anonymous function) @ app.js:582

**Comment by mygnu** [comment]
``` javascript
Vue.material.theme.registerAll({
  default: {
    primary: 'cyan',
    accent: 'pink'
  },
  phone: {
    primary: 'indigo',
    accent: 'pink'
  }
});
```
works

**Comment by marcosmoura** [comment]
I already know what's happening. I'll fix this ASAP. Thank you.

**Comment by mygnu** [comment]
Hey @marcosmoura I have another question??
what other libraries i need to include to be able to work with vue-material i.e.
materialize.js || jquery.js etc all the other material libs require this. and you might want to add this to the docs as well.
Thank You

**Comment by marcosmoura** [comment]
You don't need to include any other library. The focus of this project is
to have a standalone build with no external dependence, but aiming to
deliver the best experience without break the compatibility with the Vue.js
core. So you only need to import VueMaterial and you're good to go.

**Comment by marcosmoura** [comment]
Also I want to make everything cleaner as possible, so the current
dependencies will be dropped in a near future. Everything that depends on
those three dependencies will be develop from scratch and in a "Vue
syntax". I will make Vue Material complete enough to be easy to integrate
with other tools, like vue-validator, for forms for example. :D

**Comment by mygnu** [comment]
that's awesome man. I'm creating a branch of my project now using vue-material and will implement as things become available..
PS I'm still learning but happy to help where I can.

**Comment by marcosmoura** [comment]
Oh. Great to hear that. You can follow the updates on this URL too:
http://marcosmoura.github.com/vue-material

Thank you.
