### ISSUE TITLE
[Feature request] New components

### ISSUE THREAD

**Issue by fergardi** [marcosmoura/vue-material#322]
Hello!

First of all, loving your work, seriously. When a coworker discovered me vue, It was amazing, but I am more framework-friendly than a craft all by myself kind of person. I really enjoy making materialized vue apps. Some questions/improvements, thought:

Can the chips have an icon/avatar embed, like in https://material.io/guidelines/components/chips.html#chips-contact-chips?

Can the snackbar have customized theming using md-theme component?

Can you implement toasts/steppers?

Can the sidenav open on a swipe (swipeleft/swiperight) touch action using https://github.com/vuejs/vue-touch like in mobile devices? I managed to use the new beta version for vue 2.0 and built an app with Cordova but vue-router seems to capture my touch action instead the md-touch custom component I declared in order to open the sidenav. So I'd love a built-in solution instead.

Can you build a detailed and documented example of a full responsive multicolumn md-layout? I'm having a really hard time understanding this one, went from bootstrap-like grids and have no clue.

**Comment by marcosmoura** [comment]
Hi @fergardi 

First of all, it's better to open a different issue per subject, to make it better to track and to not merge two or more discussions. But I will answer all of them here :)

**Can the chips have an icon/avatar embed**
Yes. This will be added as a new component: md-contact-chips

**Can the snackbar have customized theming using md-theme component?**
What do you mean? You want different backgrounds? Of so, this is not going to be implemented. The snackbar should not have accent, primary or warn colors. Except for the actions that can have different colors.

**Can you implement toasts/steppers?**
I will think about the toast, because this component is ONLY for Android Apps. The steppers will be developed, but I haven't prioritized yet, so I cannot say when it's going to be delivered.

**Can the sidenav open on a swipe (swipeleft/swiperight) touch action**
This is duplicated. #275 #44 
But I will integrate the vue-touch in the project, for tabs, switch, sidenav, snackbar (to dismiss), and some upcoming components, like the date/time pickers, bottom sheets, swipe to refresh, onboarding and feature discovery.

**Can you build a detailed and documented example of a full responsive multicolumn md-layout?**
What do you need specifically? A guide on how to change the column size for a specific breakpoint size? I can create a example on Codepen...

Thank you!

**Comment by abotsi** [comment]
Hi, 
Nice library, thanks for your work! I'm also looking for the stepper component, could you tell which level is this feature in your todo list? Do you maybe need some help to develop it?
