### ISSUE TITLE
Menu doesn't open inside list item in Firefox

### ISSUE THREAD

**Issue by zanchi** [marcosmoura/vue-material#325]
### Steps to reproduce
Have an `md-menu` inside of an `md-list-item`. It opens when clicked in Chrome 55 and Edge 25 but not Firefox.
### Which browser?
Firefox 50.1.0
### What is expected?
The menu should open inside the list item.
### What is actually happening?
Menu is not opening
### Reproduction Link
https://codepen.io/Zanchi/pen/ggPVKo

I found [issue 237](https://github.com/marcosmoura/vue-material/issues/237) but I'm not sure if it's related.

**Comment by korylprince** [comment]
This appears to happen because the click event for the `md-menu-trigger` is not firing. I'm pretty sure this happens because firefox doesn't fire click events for sub-elements of `<button>`.

The problem ultimately occurs because putting a md-menu in an md-list causes the final rendering to be a <button> in a <button> and the inner-most button (menu trigger) click events do not fire.

The only way to fix this, it would seem, is to either force firefox to send click events somehow (I haven't found a way yet) or change md-list-item to not render as a button.

Since the HTML5 spec disallows buttons in buttons, I'd say the latter is the correct solution. 

I looked at [angular-material](https://material.angularjs.org/latest/demo/list) and it seems to have some conditional rendering going based on if there's a secondary menu inside. But it also creates a button thats a sibling to the content instead of a parent to it, so perhaps that is an option as well.
