### ISSUE TITLE
Props vs. Using Refs to call Methods.

### ISSUE THREAD

**Issue by prograhammer** [marcosmoura/vue-material#349]
Firstly...this is an excellent project! This is some really great work, probably one of the top Vue projects on Github in my opinion, please keep going!

Now here's my **thought / recommendation**: Do you think more props would be good in addition to the refs to get at the child methods? For example, let's say I use a child sidenav in my parent template like this:

```
  <md-sidenav 
    class="pm-sidenav md-left md-fixed"
    v-if="auth.isLoggedIn"
    ref="sidenav" 
    :open="$store.state.isSidenavOpen"   <-- prefferred approach (one liner!)
  > ... 
  </md-sidenav>
```

Notice the prop `:open`. Currently this prop **does not exist** in `md-sidenav`. But this prop would be better than using the child method directly (`this.$refs.sidenav.open()`). 

Here's what I have to do in my parent component right now:

```
  // current approach (much more verbose)
  computed: {
    isSidenavOpen: function () {
      const isOpen = this.$store.state.isSidenavOpen
      if (this.$refs.sidenav && isOpen) {
        this.$refs.sidenav.open()         // <-- introduces a side effect!
      }
      return this.$store.state.isSidenavOpen
    }
  }

  // Or another option is to use this.$store.watch...
```
This is much more verbose compared to this: `:open="$store.state.isSidenavOpen"`.
Maybe each public method also gets a prop that works too (something stated in a general way in the docs).
What do you think?

**Comment by marcosmoura** [comment]
Eventually the "ref" way of calling the inner methods will die. Of course that will work, but I will develop a better way using "event buses"
Why not using props? Because some components need to tell the parent that some action happened. Using the md-sidenav as an example:
```vue
 <md-sidenav class="md-left md-fixed" :open="isOpened"> ... </md-sidenav>
```

This example kinda works. If the user clicks in the backdrop to close the sidenav, I can't update de "isOpened" variable internally. This will be a problem. As a workaround we could use the exposed events to update the variable, but this may cause some confusions.

In the near future this will be replaced by "services" like that:
```vue
 <md-sidenav class="md-left md-fixed" id="left-drawer"> ... </md-sidenav>
```
```js
import mdSidenav from VueMaterial

...

methods: {
  openSidenav() {
    mdSidenav.open('left-drawer')
  }
}
```
