### ISSUE TITLE
update form 0.6.3 to 0.7.1 sidenav stops working

### ISSUE THREAD

**Issue by eackland** [marcosmoura/vue-material#506]
I updated the version and the sidenav i had working fine with version 0.6.3 doesn't work. Also i had a nested accordion menu which worked fine but doesn't in the new version...

**Comment by marcosmoura** [comment]
Can you provide some code examples?

**Comment by praneetloke** [comment]
@eackland I had the same problem at first. But in my case it turned out that the menu trigger button needs the `.native` modifier since 0.7.1. The same solution applied to a few more components too actually, starting from 0.7.1. Also, as @marcosmoura pointed out, please fill out the bug template in your comment.

**Comment by marcosmoura** [comment]
@eackland Your problem is similar to @praneetloke?

**Comment by web-surfer** [comment]
Having the same problem with my sidebar. Have a nested accordion menu in the sidebar that no longer works.

@praneetloke where did you add the `.native` modifier? Where are the 'menu trigger buttons' for list items?

**Comment by praneetloke** [comment]
@web-surfer I had to add it to the @click(or v-on:click) handlers. For list items, the event handlers are in the list items themselves. If you post a codepen link, I could help you better.
