### ISSUE TITLE
[md-tabs][v-for] Tabs not showing when created dynamically

### ISSUE THREAD

**Issue by lkettenb** [marcosmoura/vue-material#580]
Please have a look at this simple [fiddle](https://jsfiddle.net/8w8tfsx0/). 

When I try to load my tabs dynamically I get the following error (see console output):

> TypeError: Cannot read property 'ref' of undefined
    at VueComponent.<anonymous> (vue-material@0.7.1:9)
    at Array.<anonymous> (vue@2.2.1:464)
    at nextTickHandler (vue@2.2.1:413)
logError @ vue@2.2.1:426

**Comment by bolerodan** [comment]
Yup, I tracked down this bug that happens to tabs being registered after the <md-tab> component has been initialized with no tab list (since you are populating tabs after).

The fix for @marcosmoura  seems to be in registerTab method, to check if the tablist is empty and if no activeTab is set, if not, then set this first registered tab as the active one.

I could probably do a PR but the fix is fairly simple.

**Comment by marcosmoura** [comment]
Already fixed!

**Comment by pedro-meza** [comment]
Here is some some code for mdTabs, that has not been refactored for efficiency

registerTab:function(t){

    let hasActive = false;
    for(let tab of Object.keys(this.tabList)){
      if(this.tabList[tab].active) hasActive = true;
    }
    this.tabList[t.id] = t;
    if(!hasActive) this.tabList[t.id].active = true;
  },

**Comment by pablohpsilva** [comment]
@pedro-meza could you please make a PR with this change? 
We'll be super happy with it :D
