### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by praneetloke** [marcosmoura/vue-material#598]
So, is this project dead? PRs, and issues are piling up without any comments from maintainers. Just wondering..

**Comment by Ranmus** [comment]
I hope not, because i'm waiting for official release with datepicker component...

**Comment by cawa-93** [comment]
I hope so too. After all, I, like many people expect the support SSR

**Comment by Samuell1** [comment]
Its not dead @marcosmoura working last on https://github.com/marcosmoura/vue-material/tree/components/mdDatepicker 6 days ago, but maybe he is very busy.

I think this project needs one more maintainer to split the work.

**Comment by fergardi** [comment]
I'm also worried to see only an official release per month or so. Usually I'm working on custom components to collaborate, and using this project in personal projects too, so I wish this is not the end!

**Comment by marcosmoura** [comment]
It's not dead at all. I'm on vacations. :)

**Comment by praneetloke** [comment]
Closed this. The man himself has replied.

**Comment by marcosmoura** [comment]
Just to clarify:

The project is in the middle of the process to become stable. After the next components, as the Date Picker and Autocomplete, for example, I will focus on improvements to the features that we already have and release a 1.0.0 version. There is some things planned, like some CLI templates and boilerplates, Codepen examples, SSR support and many other core features... So there is a lot of work to do!

I'm sorry for all the issues without answer. I'll focus and work hard to fix all the bugs, implement all the new features and help all of you. After the famous Carnaval party here in Brazil, I scheduled my vacations, and as I never had that in my life, I'm trying to rest as much as I can.

The fact is that I run this project alone, as a side project, and in my absence the amount of issues will increase dramatically. I didn't expect that this project would have that large amount of regular users, which is just **AMAZING**! But I will try to fix that bringing core contributors in the near future.

But one thing is clear: This project **IS NOT** going to die. :)

**Comment by craigvantonder** [comment]
@marcosmoura I love vue-material, one of my most favorite things on the web. Really appreciate all of your hard work here, one day when I am not so much of a huge noob I hope that I can contribute in some way too.

The guy mumbling about one official commit per month is nowhere near accurate, you deserve to enjoy your holidays, thanks man! ;)

**Comment by praneetloke** [comment]
Thanks for the explanation, @marcosmoura. I would like to submit few more PRs as far as fixes for issues go. I wanted to know if I should invest time in submitting them or wait to see some activity. It is good to know that you are committed to this project. Clearly, there are a lot of people who love what you are doing and are eager help with this project, including myself. It has been clear to a lot of us (on gitter chat) that you are managing this repo all by yourself but we wanted to know what was going on.

Hope you are enjoying your time-off :)

**Comment by Morgul** [comment]
I also want to give my support for this project. I use it in a lot of my personal projects, and many internal tools at work (we're actually transitioning _all_ of our internal developer tools over toe Vue2/Vue Material) so I have some pretty strong feelings about seeing this project grow and improve.

For the time being, @marcosmoura, is it helpful if community members do some initial reviews on the pull requests? Since GitHub allows anyone to do a review (I've done a few for this project already), it might help triage some of the influx of contributions, before you get more maintainers onboarded. The only thing the community can't do on it's own is accept pull requests. :)

Put it another way; if we love the project so much, why don't we try and help lighten @marcosmoura's burden?

**Comment by craigvantonder** [comment]
I remember seeing this opened for help wanted: https://github.com/marcosmoura/vue-material/issues/84

I think this was implemented partially here: https://vuematerial.github.io/#/getting-started and here: https://vuematerial.github.io/#/themes/configuration

Looked through the commits to try to see how this was done but have not found them. @praneetloke / @Morgul would you help me to get a PR together which implements Codepen for a single example? I think with code for one it would make it a lot easier to understand and work on implementing it for the rest of the docs site.

I think that there are a lot of smart people who are already making use of this and if we all spent a little bit of time trying to help each other then that would enable the project to grow at a faster pace. 

I started the vue-material tag on Stack Overflow but it seems that it's not being used very much and I do see some question type issues popping up. Also see that Gitter is not being used very much. Why not try to make it more so that questions are addressed by the community on Gitter/SO/Twitter/Etc and if @marcosmoura does have some time available and feels like helping us all then he can try to but let's be real, that takes time and effort.

Saw someone mention on Gitter about Patreon, I think it's a good idea too and would love to see some way to make a donation. I backed the Fontawesome Kickstarter and it was amazing to see the how we as a community of developers can come together to make a big impact on how things are being done in any given project that has a decent user base. I also think that if I was making use of this project on a commercial basis then I would be even more happy to offer something towards the time and effort that has gone into this, maybe even pay for the time and effort in helping me to solve a problem too.

**Comment by Morgul** [comment]
@craigvantonder The relevant bits I've been able to find are here:

* https://blog.codepen.io/documentation/api/prefill/
* https://blog.codepen.io/documentation/features/embedded-pens/

If I'm following; there isn't an API for updating a Pen, only 'prefilling' a new Pen. So, all the examples can be created as Pens, but they will need to be updated by hand when things change.

Alternatively, we can transition all the code examples to the codepen style json objects, and then render them in much the same way as they are now, but create an 'Edit on Codepen' button that uses the prefill API to start a new Pen. This is as easy and automatic as the current code examples (with all the same downsides, as well), but adds the ability for people to play with the code examples easier.

In either case, the examples need to be rewritten in codepen's json format, so that might be a good place to start.

**Comment by silviogreuel** [comment]
Carnaval Caralho!

**Comment by marcosmoura** [comment]
I'm back!

**Comment by Andkoo** [comment]
@marcosmoura can you please merge #651 ? I really need it for my project...like...you know...REALLY

**Comment by Samuell1** [comment]
@marcosmoura I think its dead again :D , can we get permissions for some of contributors to manage vue-material too? <3

**Comment by hoopyfrood** [comment]
+1 the lack of activity is a little alarming, happy to offer help!

**Comment by d3radicated** [comment]
@Samuell1 Or can we create a fork of this repo and collaborate there?

**Comment by Samuell1** [comment]
Repost from gitter (https://gitter.im/vuematerial/Lobby?at=58efce8af22385553d3b2baf):

> Marcos Moura @marcosmoura
> I'm alive and well! Just so caught in my new job. Sorry about making you guys waiting for news, but those events happens.
> Regarding contribution permission: I will give some access, but I need to clean up some issues and some small things before. Then I will pick some contributors to work in this project.
> \o/

**Comment by abelovic** [comment]
@marcosmoura - any progress on picking collaborators and moving this forward?

**Comment by fergardi** [comment]
Again, this is really disturbing...

**Comment by d3radicated** [comment]
I know that we've heard from @marcosmoura last couple of weeks but I think it's taking a little too long. Is anyone willing to fork this repo?

**Comment by Samuell1** [comment]
@fergardi @d3radicated @abelovic 
he's gonna be back with the project next month... (https://gitter.im/vuematerial/Lobby?at=58efa6bca0e4856242ffaab2)

**Comment by Morgul** [comment]
@d3radicated I've been in direct contact with @marcosmoura. He said Sunday that he would be adding contributors in the next two weeks, which is consistent with the 'month' timeframe he gave @pablohpsilva previously. I feel like if we started up a fork, it would be a waste of effort, because the problem will be solved in not too many days.

If it comes down to the point where nothing is moving and we need to fork, I will gladly make one, and setup an organization and everything. But for the moment, I'm going to ask for a little more patience. I know it's frustrating; I'm frustrated as well. But this will start moving again in just a few days.

**Comment by marcosmoura** [comment]
Well. I know that it's frustrating for you. But, in my perspective, it's
really difficult to focus every single day for 2 consecutive years. I
changed my daily job recently and I took some vacation days to rest and
clear my mind. Right now I'm answering this looking at an angry sea at the
northeast side of Brazil.

Of course that I will work on this project again and there is no need to
create a official fork. Make open source projects is really hard because of
those life events but after May 2nd you guys will be able to see the issues
being resolved and the contributions reviewed.

♥

On Apr 27, 2017 12:24, "Christopher S. Case" <notifications@github.com>
wrote:

@d3radicated <https://github.com/d3radicated> I've been in direct contact
with @marcosmoura <https://github.com/marcosmoura>. He said Sunday that he
would be adding contributors in the next two weeks, which is consistent
with the 'month' timeframe he gave @pablohpsilva
<https://github.com/pablohpsilva> previously. I feel like if we started up
a fork, it would be a waste of effort, because the problem will be solved
in not too many days.

If it comes down to the point where nothing is moving and we need to fork,
I will gladly make one, and setup an organization and everything. But for
the moment, I'm going to ask for a little more patience. I know it's
frustrating; I'm frustrated as well. But this will start moving again in
just a few days.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/marcosmoura/vue-material/issues/598#issuecomment-297747933>,
or mute the thread

**Comment by Morgul** [comment]
@marcosmoura Glad to see an official response. :)

Just to clarify, it's mostly a general frustration I'm referring to. I _completely_ get the changing jobs thing, when I changed jobs a few years ago, it took me at least six months to get up to speed on all my free time projects. So, yeah, I definitely understand.

Mostly just urging patience, and trying to give some transparency to the community. :) Looking forward to seeing things move forward. 👍

**Comment by abelovic** [comment]
@marcosmoura - you have nothing to apologize for or explain! Many of us are in the same boat as you (no time for anything!) so we understand :) This is a great project and people just want to see it succeed which is a total compliment to the fantastic work you have done here. There are many talented people that are offering to help you in anyway they can (including myself). 

Thanks for taking the time to respond to us and looking forward to the next version!

**Comment by abelovic** [comment]
@marcosmoura - Now that you are an official vue-material celebrity... don't tell @Samuell1 or @Morgul you are "by the sea in Brazil" because they may actually track you down and find you there!!! lol

**Comment by DavidBradbury** [comment]
I think the frustration comes from a lack of communication. Being told that it will be a few days, and not hearing anything a week later. Having a PR open for 3 weeks without comment. It just feels disrespectful to the people who are contributing to the project to not spend maybe 15 minutes asking for people to manage while you're gone, and then add them later that day. If things go to shit, you can always fix it when ya get back.

I certainly respect you and the time you put into all of this free, open-source work. We all do. But I think that pretending that going MIA isn't disrespectful is silly. (And trust me, I understand. I just moved 3000 miles, had to find a new job, new apartment, and it's taken me a couple months to settle down).

**Comment by asadhshujau** [comment]
still waiting for new updates

**Comment by fergardi** [comment]
This was a nice project, but I'm tired of waiting. I think I'm switching to [http://www.muse-ui.org](http://www.muse-ui.org) for the moment.

See you all!

**Comment by Andkoo** [comment]
yeah this is taking literally forever...

**Comment by abelovic** [comment]
@fergardi - thanks for sharing. I have never seen this one. 

I really liked this project as well but I can't build a production app on something that hasn't been updated in months :(

I have decided to switch to https://vuetifyjs.com - tons of components, seems active, and pretty solid. It also supports SSR although I don't need this feature.

What's everyone else looking at/using?

**Comment by billouboq** [comment]
@abelovic I'm using it too but their select component and their list are not that great (prefer the flexibility of vue material one), but other than that it seems to be a great library and works good so far.

**Comment by zhangwei900808** [comment]
I  very about it

**Comment by marcosmoura** [comment]
Back to work.

**Comment by kgrosvenor** [comment]
Take donations dude, i'm sure we will all support you!

**Comment by guanzo** [comment]
Hey marco, just want to let you know i think this library is AWESOME. keep up the good work

**Comment by marcosmoura** [comment]
#921
