### ISSUE TITLE
md-input issue (v0.3.0)

### ISSUE THREAD

**Issue by javaday** [marcosmoura/vue-material#69]
The md-input component is not reactively updating its value when the model is updated unless the placeHolder property is set. Also when the placeHolder is set the value is updated, but the label is not displayed until the field is clicked.

**Comment by marcosmoura** [comment]
I see. You will get this if you use the md-input (or any other component that uses v-model) inside one of those components:
* md-card-actions
* md-card-content
* md-card-header
* md-card-header-text
* md-card-media-actions
* md-list
* md-toolbar

This is happening because of v-once being misused in all of those components. This is a bad bug. Will be fixed very soon.

Sorry about that!
Thanks!

**Comment by 0xFireball** [comment]
Thank you!

**Comment by javaday** [comment]
Thanks for the quick response!
